version: "2"
plugins:
  shellcheck:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  golint:
    # golint on codeclimate doesn't understand Go 1.18 generics yet.
    enabled: false
  fixme:
    enabled: true
exclude_patterns:
- 'config/'
- 'db/'
- 'dist/'
- 'features/'
- '**/node_modules/'
- 'script/'
- 'envtest/'
- '**/spec/'
- '**/test/'
- '**/tests/'
- 'Tests/'
- '**/vendor/'
- '**/*_test.go'
- '**/*.d.ts'
- 'e2e/lib/'
- '**/zz_generated.deepcopy.go'
