---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-exoscale-crossplane-io-v1-bucket
  failurePolicy: Fail
  name: buckets.exoscale.crossplane.io
  rules:
  - apiGroups:
    - exoscale.crossplane.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buckets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-exoscale-crossplane-io-v1-iamkey
  failurePolicy: Fail
  name: iamkeys.exoscale.crossplane.io
  rules:
  - apiGroups:
    - exoscale.crossplane.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iamkeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-exoscale-crossplane-io-v1-postgresql
  failurePolicy: Fail
  name: postgresqls.exoscale.crossplane.io
  rules:
  - apiGroups:
    - exoscale.crossplane.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - postgresqls
  sideEffects: None
