apiVersion: exoscale.crossplane.io/v1
kind: Kafka
metadata:
  creationTimestamp: null
  name: kafka-local-dev
spec:
  forProvider:
    ipFilter:
    - 0.0.0.0/0
    kafkaRestSettings: null
    kafkaSettings:
      connections_max_idle_ms: 60000
    maintenance:
      dayOfWeek: monday
      timeOfDay: "12:00:00"
    size:
      plan: startup-2
    version: "3.2"
    zone: ch-dk-2
  providerConfigRef:
    name: provider-config
  writeConnectionSecretToRef:
    name: kafka-local-dev-details
    namespace: default
status:
  atProvider:
    kafkaRestSettings: null
    kafkaSettings: null
